server:
  port: 8081
spring:
  application:
    name: sale-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/sales_db}
    username: ${SPRING_DATASOURCE_USERNAME:sales_app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 0
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
application-config:
  kafka:
    server-url: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    auto-offset-reset: "earliest"
    topic: "tp-saga-market"
    producer:
      group-id: "send-sale"
    consumer:
      group-id:
        finalize: "finalize-sale"
        cancel: "cancel-sale"
logging:
  level:
    org.springframework.core.env: DEBUG
