server:
  port: 8081
spring:
  application:
    name: sale-service
  datasource:
    url: jdbc:mysql://localhost:3308/sales_db
    username: sales_app_user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
application-config:
  kafka:
    server-url: "localhost:9092"
    auto-offset-reset: "earliest"
    topic: "tp-saga-market"
    producer:
      group-id: "send-sale"
    consumer:
      group-id:
        finalize: "finalize-sale"
        cancel: "cancel-sale"
logging:
  level:
    org.springframework.core.env: DEBUG
