server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/inventory_db
    username: inventory_app_user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
application-config:
  kafka:
    server-url: "localhost:9092"
    auto-offset-reset: "earliest"
    topic: "tp-saga-market"
    producer:
      group-id: "send-inventory"
    consumer:
      group-id:
        credit: "credit-inventory"
        debit: "debit-inventory"
logging:
  level:
    org.springframework.core.env: DEBUG
