server:
  port: 8083
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/payment_db}
    username: ${SPRING_DATASOURCE_USERNAME:payment_app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 0
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
application-config:
  kafka:
    server-url: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    auto-offset-reset: "earliest"
    topic: "tp-saga-market"
    producer:
      group-id: "send-payment"
    consumer:
      group-id: "finalize-payment"
logging:
  level:
    org.springframework.core.env: DEBUG